### ISSUE TITLE
Meetup integration

### ISSUE THREAD

**Issue by sc68cal** [aaronfeng/punchcard-io-feature-requests#1]
Rather than having users manually check in to punchcard.io - investigate using the [Meetup API](http://www.meetup.com/meetup_api/) for [checkins](http://www.meetup.com/meetup_api/docs/2/checkins/).

**Comment by aaronfeng** [comment]
Pulling meetings from meetup is on the roadmap. Not sure about meetup checkin but I can investigate. Location based with pin checkin is coming.

**Comment by aaronfeng** [comment]
@sc68cal a basic implementation has been added, but not automated for now since I'm not certain how meetup.com api will behave in all cases.  Basically, it will attempt to figure out if you are on meetup.com during meeting creation time.  If it can retrieve the upcoming meeting then it will auto populate all the fields except for keywords (which is a required field).  If the meeting has already been created, it will not auto populate.

This means the organizer will still have to login and create a new meeting, but fields will be populated.

cc/ @tpanzarella, @zorn, @kyleburton, @bmc, @nilnilnil

This code should be pushed by tomorrow.
